/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ifrhj7nwknajxaosxosvr5tjiq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:e9520d0c-c663-4084-bcbd-82d7f54ccd98",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DJbuodo2N",
    "aws_user_pools_web_client_id": "4e2ms6o0mj62iae6gs3uv40scv",
    "oauth": {},
    "aws_user_files_s3_bucket": "basicnave598a12f03ec47ca9928f22e6cb80f2b130106-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
